import React from 'react';
import {
  Utensils,
  ShoppingBag,
  Home,
  Car,
  Film,
  CreditCard,
  Zap,
  Briefcase,
  TrendingUp,
  Users,
  Heart,
  Coffee,
  Plane,
  Book,
  Gift,
  Activity,
  Tag,
  Sparkles,
  Smartphone,
  Shield,
  Music,
  Camera,
  Wifi,
  Dumbbell,
  Stethoscope,
  Scissors,
  ShoppingCart,
  Key,
  Truck,
  Laptop,
  Flame,
  GraduationCap,
  Package,
  DollarSign,
  Coins,
  Smile,
  Award,
  Bus,
  Layers,
  LucideIcon
} from 'lucide-react';

export const AVAILABLE_CATEGORY_ICONS: { name: string; label: string; icon: LucideIcon }[] = [
  { name: 'Utensils', label: 'Food & Dining', icon: Utensils },
  { name: 'ShoppingBag', label: 'Shopping', icon: ShoppingBag },
  { name: 'ShoppingCart', label: 'Groceries', icon: ShoppingCart },
  { name: 'Home', label: 'Housing & Rent', icon: Home },
  { name: 'Car', label: 'Transport & Fuel', icon: Car },
  { name: 'Bus', label: 'Public Transit', icon: Bus },
  { name: 'Film', label: 'Entertainment', icon: Film },
  { name: 'CreditCard', label: 'EMI & Cards', icon: CreditCard },
  { name: 'Zap', label: 'Utilities & Power', icon: Zap },
  { name: 'Briefcase', label: 'Salary & Work', icon: Briefcase },
  { name: 'TrendingUp', label: 'Investments', icon: TrendingUp },
  { name: 'DollarSign', label: 'Finance & Income', icon: DollarSign },
  { name: 'Coins', label: 'Savings', icon: Coins },
  { name: 'Users', label: 'Friends & Social', icon: Users },
  { name: 'Coffee', label: 'Cafe & Drinks', icon: Coffee },
  { name: 'Heart', label: 'Health & Wellness', icon: Heart },
  { name: 'Stethoscope', label: 'Medical & Pharma', icon: Stethoscope },
  { name: 'Dumbbell', label: 'Fitness & Gym', icon: Dumbbell },
  { name: 'Plane', label: 'Travel & Trips', icon: Plane },
  { name: 'Book', label: 'Education & Books', icon: Book },
  { name: 'GraduationCap', label: 'Courses & Tuition', icon: GraduationCap },
  { name: 'Gift', label: 'Gifts & Donations', icon: Gift },
  { name: 'Activity', label: 'Hobbies & Sports', icon: Activity },
  { name: 'Smartphone', label: 'Mobile & Subscriptions', icon: Smartphone },
  { name: 'Laptop', label: 'Tech & Gadgets', icon: Laptop },
  { name: 'Wifi', label: 'Internet & Broadband', icon: Wifi },
  { name: 'Music', label: 'Music & Streaming', icon: Music },
  { name: 'Camera', label: 'Photography', icon: Camera },
  { name: 'Shield', label: 'Insurance & Security', icon: Shield },
  { name: 'Key', label: 'Maintenance & Repairs', icon: Key },
  { name: 'Scissors', label: 'Personal Care & Salon', icon: Scissors },
  { name: 'Package', label: 'Courier & Delivery', icon: Package },
  { name: 'Truck', label: 'Logistics', icon: Truck },
  { name: 'Flame', label: 'Emergency Fund', icon: Flame },
  { name: 'Sparkles', label: 'Luxury & Treats', icon: Sparkles },
  { name: 'Smile', label: 'Personal', icon: Smile },
  { name: 'Award', label: 'Awards & Bonus', icon: Award },
  { name: 'Tag', label: 'General / Other', icon: Tag },
];

export const CATEGORY_PALETTES = [
  { hex: '#F97316', name: 'Tangerine Orange' },
  { hex: '#8B5CF6', name: 'Royal Purple' },
  { hex: '#EC4899', name: 'Rose Pink' },
  { hex: '#06B6D4', name: 'Ocean Cyan' },
  { hex: '#EAB308', name: 'Sunflower Yellow' },
  { hex: '#EF4444', name: 'Crimson Red' },
  { hex: '#10B981', name: 'Emerald Green' },
  { hex: '#22C55E', name: 'Vibrant Green' },
  { hex: '#6366F1', name: 'Electric Indigo' },
  { hex: '#3B82F6', name: 'Cobalt Blue' },
  { hex: '#0EA5E9', name: 'Sky Blue' },
  { hex: '#14B8A6', name: 'Teal Green' },
  { hex: '#84CC16', name: 'Lime Green' },
  { hex: '#D946EF', name: 'Fuchsia Magenta' },
  { hex: '#7C3AED', name: 'Deep Violet' },
  { hex: '#E11D48', name: 'Ruby Scarlet' },
  { hex: '#F59E0B', name: 'Golden Amber' },
  { hex: '#64748B', name: 'Slate Gray' },
  { hex: '#475569', name: 'Charcoal' },
  { hex: '#059669', name: 'Pine Forest' },
];

const iconMap: Record<string, LucideIcon> = {
  Utensils,
  ShoppingBag,
  ShoppingCart,
  Home,
  Car,
  Bus,
  Film,
  CreditCard,
  Zap,
  Briefcase,
  TrendingUp,
  DollarSign,
  Coins,
  Users,
  Coffee,
  Heart,
  Stethoscope,
  Dumbbell,
  Plane,
  Book,
  GraduationCap,
  Gift,
  Activity,
  Smartphone,
  Laptop,
  Wifi,
  Music,
  Camera,
  Shield,
  Key,
  Scissors,
  Package,
  Truck,
  Flame,
  Sparkles,
  Smile,
  Award,
  Tag,
  Layers,
};

interface CategoryIconProps {
  iconName: string;
  className?: string;
}

export const CategoryIcon: React.FC<CategoryIconProps> = ({ iconName, className = 'w-4 h-4' }) => {
  const IconComponent = iconMap[iconName] || Tag;
  return <IconComponent className={className} />;
};
